-- This module is the root of the GoldbachConjectureCanonicalLaneLean Lean proof package.
import GoldbachConjectureCanonicalLaneLean.Basic
import GoldbachConjectureCanonicalLaneLean.SourcePackage
import GoldbachConjectureCanonicalLaneLean.SourceDependencies
import GoldbachConjectureCanonicalLaneLean.Formalization
import GoldbachConjectureCanonicalLaneLean.ReviewerBridge
import GoldbachConjectureCanonicalLaneLean.TheoremStatement
import GoldbachConjectureCanonicalLaneLean.MathlibObjects
import GoldbachConjectureCanonicalLaneLean.AdmissibleClass
import GoldbachConjectureCanonicalLaneLean.Projection
import GoldbachConjectureCanonicalLaneLean.BridgeLemmas
import GoldbachConjectureCanonicalLaneLean.GateLemmas
import GoldbachConjectureCanonicalLaneLean.FinalTheorem
import GoldbachConjectureCanonicalLaneLean.MathlibStatement
